name: jobxprss_company
description: A new Flutter application for Job EXpress.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.7+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  font_awesome_flutter: ^8.8.1
  flutter_feather_icons: ^1.0.3
  rxdart: ^0.24.1
  http: ^0.12.1
  after_layout: ^1.0.7+2
  shared_preferences: ^0.5.7+3
  intl: ^0.16.1
  page_view_indicators: ^1.3.1
  uuid: ^2.1.0
  image_cropper: ^1.2.3
  image_picker: ^0.6.7+2
  #  flutter_html: ^1.0.0
  package_info: ^0.4.1
  dartz: ^0.9.1
  google_fonts: ^1.1.0
  bot_toast: ^3.0.0
  url_launcher: ^5.4.11
  cached_network_image: ^2.2.0+1
  flutter_image_compress: ^0.6.8
  equatable: ^1.2.0
  #  device_id: ^0.2.0
  connectivity: ^0.4.8+6
  logger: ^0.9.1
  get_it: ^4.0.2
  #  searchable_dropdown: ^1.1.3
#  autocomplete_textfield: ^1.7.3
  flutter_typeahead: ^1.8.3
  #  animations: ^1.0.0+5
#  firebase_messaging: ^6.0.16
#  firebase_core: ^0.4.5
  google_maps_flutter: ^0.5.28+1
  webview_flutter: ^0.3.22+1
  charts_flutter: ^0.9.0
  shimmer: ^1.1.1
  percent_indicator: ^2.1.5
  jwt_decode: ^0.1.0
  flutter_html: ^0.11.0
#  flutter_gifimage: ^1.0.1
#  dropdown_search: ^0.4.3
#  html_editor: ^1.0.1
  http_extensions_cache: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
