name: jobxprss_company
description: A new Flutter application for Job EXpress.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 0.0.16+16

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.2+1
  font_awesome_flutter: ^8.8.1
  flutter_feather_icons: ^1.0.3
  rxdart: ^0.24.1
  http: ^0.12.2
  after_layout: ^1.0.7+2
  shared_preferences: ^0.5.10
  intl: ^0.16.1
  page_view_indicators: ^1.3.1
  uuid: ^2.2.2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+7
  package_info: ^0.4.3
  dartz: ^0.9.1
  google_fonts: ^1.1.0
  bot_toast: ^3.0.4
  url_launcher: ^5.5.0
  cached_network_image: ^2.3.1
  flutter_image_compress: ^0.7.0
  equatable: ^1.2.4
  connectivity: ^0.4.9+2
  logger: ^0.9.2
  get_it: ^4.0.4
  flutter_typeahead: ^1.8.8
  google_maps_flutter: ^0.5.30
  webview_flutter: ^0.3.22+1
  charts_flutter: ^0.9.0
  shimmer: ^1.1.1
  percent_indicator: ^2.1.5
  jwt_decode: ^0.1.0
  dropdown_search: ^0.4.4
  flutter_cache: ^0.0.6
  permission_handler: ^5.0.1+1
  geolocator: 5.3.2+2
#  flutter_summernote:
#    git:
#      url: git://github.com/shofizone/flutter_summernote.git
  flutter_widget_from_html_core: ^0.4.3
  quill_delta: ^1.0.2
  notustohtml: ^0.0.7
  zefyr: ^0.11.0
  flutter_linkify: ^3.1.3
  social_share: ^2.0.5
  get: ^3.8.0
  velocity_x: ^0.4.1

dependency_overrides:
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr


dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_flavorizr: ^1.0.7


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_sq.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/certification/

#flavorizr:
#  app:
#    android:
#      flavorDimensions: "flavor-type"
#    ios:
#
#  flavors:
#    prod:
#      app:
#        name: "Job Xprss Company"
#
#      android:
#        applicationId: "com.ishraak.jobxprss_company"
#
#      ios:
#        bundleId: "com.ishraak.jobxprss_company"
#
#    dev:
#      app:
#        name: "Job Xprss Company Dev"
#
#      android:
#        applicationId: "com.ishraak.jobxprss_company_dev"
#      ios:
#        bundleId: "com.ishraak.jobxprss_company_dev"
